Feature/responsive card
Sybit-Education/Coding-Camp-2020 pull request #60
Opened 2020-10-30 15:53 UTC by stritti

2020-11-02 09:57 UTC, jonasdegener approved these changes

2020-11-02 10:52 UTC, chrisWolter requested changes
Der Abstand vom unteren Text zur Kante stimmt jetzt nicht mehr. 
![image](https://user-images.githubusercontent.com/48556854/97860090-daebee80-1d01-11eb-8e83-f64effe5a39b.png)

2020-11-09 20:00 UTC, stritti commented
> Der Abstand vom unteren Text zur Kante stimmt jetzt nicht mehr.
> ![image](https://user-images.githubusercontent.com/48556854/97860090-daebee80-1d01-11eb-8e83-f64effe5a39b.png)

jetzt ist es besser. Kannst du noch mal schauen @chrisWolter?

2020-11-16 09:06 UTC, chrisWolter commented
Die Höhe passt jetzt.
Irgendwie wird aber noch ein weiterer Text rein gerendert, wodurch ein vertical scrolll Möglich ist.

![image](https://user-images.githubusercontent.com/48556854/99233297-587c2800-27f3-11eb-9133-54bf50e54487.png)

2020-11-24 12:48 UTC, chrisWolter requested changes
Die Höhe passt nicht, da dort ein anderes Textfeld reingerendert wird. Siehe Kommentar drüber.

2020-11-26 16:42 UTC, stritti commented
> Die Höhe passt nicht, da dort ein anderes Textfeld reingerendert wird. Siehe Kommentar drüber.

So, jetzt sollte es aber passen.

2020-11-30 11:57 UTC, chrisWolter approved these changes

2020-11-30 13:12 UTC, merged