#72 redesign cards
Sybit-Education/Coding-Camp-2020 pull request #81
Opened 2020-12-17 10:59 UTC by stritti

See #72

2020-12-18 07:46 UTC, mirko-pleli requested changes

2020-12-18 07:46 UTC, mirko-pleli commented on src/components/cards/ImpulseCard.vue
>  <style lang="scss" scoped>
I like your new redesign great work. What I would improve is this view problem I have:
![image](https://user-images.githubusercontent.com/29863859/102588174-50264e00-410d-11eb-9304-87cc18d5cb97.png)
If you look to the button, the card frame disappears in our navbar.

2020-12-18 13:50 UTC, chrisWolter requested changes
Kann man die Karten in der mobilen Ansicht noch in der höhe zentrieren? Dann hängen sie im Iphone X nicht so am Header.

2020-12-18 13:50 UTC, chrisWolter commented on src/components/cards/ImpulseCard.vue
> +            <h4>Was bringt das mir?</h4>
Würden die Überschrift anders benenen. "Was bringt es mir" klingt da besser.

2020-12-18 13:50 UTC, chrisWolter commented on src/components/cards/ImpulseCard.vue
> +          <category-label :categoryId="impulse.category" />
Ich würde hier noch ein bisschen Abstand zur Überschrift setzen.

2020-12-22 16:26 UTC, stritti commented
> Kann man die Karten in der mobilen Ansicht noch in der höhe zentrieren? Dann hängen sie im Iphone X nicht so am Header.

Das zerhaut dann immer das Layout. Ich lass das erst mal.

2020-12-22 16:26 UTC, merged